//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab4_klient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IZadanie2")]
    public interface IZadanie2 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZadanie2/Test", ReplyAction="http://tempuri.org/IZadanie2/TestResponse")]
        string Test(string arg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZadanie2/Test", ReplyAction="http://tempuri.org/IZadanie2/TestResponse")]
        System.Threading.Tasks.Task<string> TestAsync(string arg);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IZadanie2Channel : Lab4_klient.ServiceReference1.IZadanie2, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Zadanie2Client : System.ServiceModel.ClientBase<Lab4_klient.ServiceReference1.IZadanie2>, Lab4_klient.ServiceReference1.IZadanie2 {
        
        public Zadanie2Client() {
        }
        
        public Zadanie2Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Zadanie2Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Zadanie2Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Zadanie2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Test(string arg) {
            return base.Channel.Test(arg);
        }
        
        public System.Threading.Tasks.Task<string> TestAsync(string arg) {
            return base.Channel.TestAsync(arg);
        }
    }
}
