//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Koduj", ReplyAction="http://tempuri.org/IService1/KodujResponse")]
        void Koduj(string nazwa, string tresc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Koduj", ReplyAction="http://tempuri.org/IService1/KodujResponse")]
        System.Threading.Tasks.Task KodujAsync(string nazwa, string tresc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Pobierz", ReplyAction="http://tempuri.org/IService1/PobierzResponse")]
        string Pobierz(string nazwa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Pobierz", ReplyAction="http://tempuri.org/IService1/PobierzResponse")]
        System.Threading.Tasks.Task<string> PobierzAsync(string nazwa);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Client.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Client.ServiceReference1.IService1>, Client.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Koduj(string nazwa, string tresc) {
            base.Channel.Koduj(nazwa, tresc);
        }
        
        public System.Threading.Tasks.Task KodujAsync(string nazwa, string tresc) {
            return base.Channel.KodujAsync(nazwa, tresc);
        }
        
        public string Pobierz(string nazwa) {
            return base.Channel.Pobierz(nazwa);
        }
        
        public System.Threading.Tasks.Task<string> PobierzAsync(string nazwa) {
            return base.Channel.PobierzAsync(nazwa);
        }
    }
}
